### PR TITLE
Treat timeout=0 as timeout disable

### PR DESCRIPTION
**Pull request by steveck-chung**

### CODE REVIEW

**Comment by steveck-chung** [comment]
First version for review, test is not added yet since some problem in test environment setup. Will add it if this patch is fine.

**Comment by steveck-chung** [comment]
@wilsonpage In this patch I check the timeout and ignore the setTimeout when timeout=0. It seems we can set silentTimeout for same result, but leaving the this.timeout to always null might be more clean. Anyway it's up to you :)

**Comment by steveck-chung** [comment]
Hi @gmarty  Would you be able to review this small feature since @wilsonpage is away?

**Comment by wilsonpage** [comment]
Amended the patch slightly replacing `0` with `false`.

**Comment by wilsonpage** [comment]
Landed c926d989e4c10e557c0e76c6710ddfff0fea6d78

**Pull request closed without merging**
